# Generated by Django 5.0.6 on 2024-05-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0002_remove_billing_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_type',
            new_name='room_category',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='branch_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='branch_initial',
            new_name='initial',
        ),
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Draft'), ('C', 'Coming Soon')], default='C', max_length=1),
        ),
    ]
