# Generated by Django 5.0.6 on 2024-05-19 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi mobile number.', regex='^\\+880?\\d{10}$|^0\\d{10}$')])),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
