# Generated by Django 5.0.6 on 2024-05-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('segment', '0003_rename_room_type_booking_room_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('A', 'Active'), ('O', 'Out of order')], default='A', max_length=1)),
                ('overview', models.TextField()),
                ('breakfast_opening', models.TimeField()),
                ('breakfast_closing', models.TimeField()),
                ('lunch_opening', models.TimeField()),
                ('lunch_closing', models.TimeField()),
                ('dinner_opening', models.TimeField()),
                ('dinner_closing', models.TimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='segment.branch')),
                ('cuisine', models.ManyToManyField(to='refuel.cuisine')),
            ],
        ),
    ]
