# Generated by Django 5.0.6 on 2024-05-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refuel', '0003_restaurant_created_at_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='area',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
